# Development Environment

version: '3'

services:
  database:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: analytics
    ports:
      - 5432:5432

  db-migrate:
    image: docker.pkg.github.com/znck/thesemetrics/db:latest
    build:
      context: database
    command: npm run migrate
    restart: 'no'
    environment:
      POSTGRES_URL: postgresql://user:pass@database:5432/analytics
    depends_on:
      - database

  app:
    image: docker.pkg.github.com/znck/thesemetrics/app:latest
    build:
      context: app
    environment:
      POSTGRES_URL: postgresql://user:pass@database:5432/analytics
    ports:
      - 3000:3000
    depends_on:
      - database

  pixel:
    image: docker.pkg.github.com/znck/thesemetrics/pixel:latest
    build:
      context: pixel
    environment:
      POSTGRES_URL: postgresql://user:pass@database:5432/analytics
    ports:
      - 3001:3001
    depends_on:
      - database
